# web server
[Server]
Addr = "127.0.0.1:8181"
ReadTimeout = 180
WriteTimeout = 180

# rabbitMQ
[RabbitMQ]
DialUrl = "amqp://admin:admin@localhost:5672/"

[RabbitMQ.MsgExchange]
Name = "messaging"
Type = "fanout"
Durable = true
AutoDeleted = false
Internal = false
NoWait = false

[RabbitMQ.MsgQueueDeclare]
Name = ""
Durable = false
DeleteWhenUnused = false
Exclusive = true
NoWait = false

[RabbitMQ.MsgQueueBind]
RoutingKey = ""
Exchange = "messaging"
NoWait = false

[RabbitMQ.MsgConsume]
Consumer = ""
AutoAck = true
Exclusive = false
NoLocal = false
NoWait = false

[RabbitMQ.MsgRespExchange]
Name = "messaging_resp"
Type = "fanout"
Durable = true
AutoDeleted = false
Internal = false
NoWait = false

[RabbitMQ.MsgRespPublish]
Exchange = "messaging_resp"
Mandatory = false
Immediate = false